// This file is automatically generated. Do not edit it directly.
import { createClient } from '@supabase/supabase-js';
import type { Database } from './types';

const SUPABASE_URL = "https://ynengaggbkwabjupktnz.supabase.co";
const SUPABASE_PUBLISHABLE_KEY = "eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJpc3MiOiJzdXBhYmFzZSIsInJlZiI6InluZW5nYWdnYmt3YWJqdXBrdG56Iiwicm9sZSI6ImFub24iLCJpYXQiOjE3NTQyNzk0MjAsImV4cCI6MjA2OTg1NTQyMH0.hvA10z-A696N5Rt3GDkkMvbN6EcPeD6jmuwhc6enUO0";

// Import the supabase client like this:
// import { supabase } from "@/integrations/supabase/client";

export const supabase = createClient<Database>(SUPABASE_URL, SUPABASE_PUBLISHABLE_KEY, {
  auth: {
    storage: localStorage,
    persistSession: true,
    autoRefreshToken: true,
  }
});